# Generated by Django 4.0.6 on 2022-08-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_customer_id_notifications_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(max_length=15),
        ),
    ]
