# Generated by Django 4.1 on 2022-09-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_currency_alter_third_party_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='proile_picture',
            new_name='profile_picture',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Wallet',
            new_name='wallet',
        ),
    ]
